### ISSUE TITLE
build failure when hero-z-7045-builder: asking for password

### ISSUE THREAD

**Issue by speedzheng** [pulp-platform/hero-sdk#28]
Hi,

 I am trying to build HERO SDK but met the following error when run ./hero-z-7045-builder -A command. Do you miss something? Thanks!

sdk:hal:prepare (hero-z-7045@config_file=/home/speedzheng/hero/hero-sdk/pulp-sdk/configs/json/hero-z-7045.json): make header
make: Nothing to be done for 'header'.
Reached EOF with exit status 0

MODULE jtag-bridge:jtag-bridge command checkout
Cloning into '/home/speedzheng/hero/hero-sdk/pulp-sdk/tools/jtag-bridge'...
git@iis-git.ee.ethz.ch's password: 
Permission denied, please try again.
git@iis-git.ee.ethz.ch's password: 
Permission denied, please try again.
git@iis-git.ee.ethz.ch's password:

**Comment by vogelpi** [comment]
Hi,
thanks for reporting the issue. It seems that the builder tries to checkout three repositories from our internal server. These should not be needed anymore. But I am currently doing a complete rebuild without these repositories to be sure.
We let you know asap.

Best regards,
Pirmin

**Comment by vogelpi** [comment]
We could fix the issue and successfully tested it on the board. Please checkout the latest tag `v1.0.1`.

Best regards,
PIrmin

**Comment by speedzheng** [comment]
Thanks for quick answer. very appreciate.
________________________________

**Comment by speedzheng** [comment]
Hi,

  I just clone the rel-v1.0.1-rc2 but met another similar error and did I clone the wrong branch?

git checkout -b <new-branch-name>

HEAD is now at 34a9206 Fixed bug, register 0 was sometimes written

sdk:vp:checkout: make checkout

MODULE pulp-rt:pulp-rt command checkout
HEAD is now at e923766 Few fixes for software implementation of barriers and locks

MODULE pc_analyzer:pc_analyzer command checkout
Cloning into '/home/speedzheng/hero/hero-sdk/pulp-sdk/tools/pc_analyzer'...
git@iis-git.ee.ethz.ch's password:

**Comment by vogelpi** [comment]
Hi,

it seems that the builder wants to build more modules than actually needed. Unfortunately, I cannot fix it right now. Can you please try the following:

In `hero-sdk`, open the file `hero-z-7045-builder` and then you comment Line 83, i.e.,
`make env all`
turns into
`#make env all`

Then you do again `hero-z-7045-builder -A`. Please let me know if it works.

Best regards,
Pirmin

**Comment by alessandrocapotondi** [comment]
Dear @speedzheng,
    thanks for your reports. I see the problem and I am fixing right now. I will push the fix as soon as I finish to test it.

Best,
Alessandro

**Comment by speedzheng** [comment]
Hi, just tried but same issue. Do you need to sync to rel-v1.0.1-rc2 again? Thanks!


Reached EOF with exit status 0
git submodule update --init
./pulp-tools/bin/plpbuild --p sdk checkout build --stdout

MODULE pc_analyzer:pc_analyzer command checkout
Cloning into '/home/speedzheng/hero/hero-sdk/pulp-sdk/tools/pc_analyzer'...
git@iis-git.ee.ethz.ch's password:

**Comment by alessandrocapotondi** [comment]
It is not yet merged. I will merge it into the `master` and I will let you know.

**Comment by speedzheng** [comment]
Now it works. Thanks for great support.

**Comment by accuminium** [comment]
Thanks for your feedback!
