### ISSUE TITLE
Vivado's version of cmake causes build failure.

### ISSUE THREAD

**Issue by DaveMcEwan** [pulp-platform/hero-sdk#40]
Can the build instructions in the README please note that sourcing vivado's settings64.sh in ~/.bashrc or ~/.bash_profile will cause the build to fail at pulp-sdk.
Vivado's version of cmake will be found on $PATH first which is too old and causes breakage without a helpful error message.
 
I asked about this here: https://pulp-platform.org/community/showthread.php?tid=46

I'd suggest some simple text like this in the section "Build the HERO SDK from the sources":
"Make sure your bash setup does not source Vivado's settings64.sh as this will prevent the build succeeding."

**Comment by alessandrocapotondi** [comment]
Dear @DaveMcEwan,
   thanks for your report. I will added the error to the https://github.com/pulp-platform/hero-sdk/blob/master/FAQ.md and I created a PR that will be integrated soon.

Thanks,
Alessandro
