### ISSUE TITLE
Build Failed HERO-SDK

### ISSUE THREAD

**Issue by khatatbih** [pulp-platform/hero-sdk#44]
LSB Version:	core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

When I try to build HERO-SDK in Ubuntu by using the following command: ./hero-z-7045-builder -A  . I get the following message 

libtool: link: gcc -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Wstack-usage=262144 -I/home/khatatbih/Desktop/HERO/hero-sdk/hero-gcc-toolchain/src/binutils/binutils/../zlib -g -O2 -static-libstdc++ -static-libgcc -o objcopy objcopy.o not-strip.o rename.o rddbg.o debug.o stabs.o ieee.o rdcoff.o wrstabs.o bucomm.o version.o filemode.o  ../bfd/.libs/libbfd.a -L/home/khatatbih/Desktop/HERO/hero-sdk/hero-gcc-toolchain/build/arm-linux-gnueabihf/binutils/zlib -lz ../libiberty/libiberty.a -ldl
collect2: error: ld returned 1 exit status
Makefile:816: recipe for target 'objcopy' failed
make[4]: *** [objcopy] Error 1
make[4]: Leaving directory '/home/khatatbih/Desktop/HERO/hero-sdk/hero-gcc-toolchain/build/arm-linux-gnueabihf/binutils/binutils'
Makefile:1004: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/home/khatatbih/Desktop/HERO/hero-sdk/hero-gcc-toolchain/build/arm-linux-gnueabihf/binutils/binutils'
Makefile:663: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/khatatbih/Desktop/HERO/hero-sdk/hero-gcc-toolchain/build/arm-linux-gnueabihf/binutils/binutils'
Makefile:3611: recipe for target 'all-binutils' failed
make[1]: *** [all-binutils] Error 2
make[1]: Leaving directory '/home/khatatbih/Desktop/HERO/hero-sdk/hero-gcc-toolchain/build/arm-linux-gnueabihf/binutils'
Makefile:850: recipe for target 'all' failed
make: *** [all] Error 2
ERROR: build_arm_toolchain failed, aborting now.

**Comment by alessandrocapotondi** [comment]
Dear @khatatbih,

thanks for your post. Did you solve your own problem?

I am interest to know frequent issues faced by the users, so if you think your solution can be useful to other users please share it with us.

Best,
Alessandro
