### ISSUE TITLE
Miss handled PULP device termination

### ISSUE THREAD

**Issue by alessandrocapotondi** [pulp-platform/hero-sdk#7]
Probably already fixed. @vogelpi, is it true?

**Comment by vogelpi** [comment]
I changed the host libgomp to cleanup the devices inside the fini function.

**Comment by vogelpi** [comment]
However, this does not help with the issue that the devices/the hardware are initialized and de-initialized multiple times.

**Comment by alessandrocapotondi** [comment]
Fixed.
